import 'package:flutter/widgets.dart';

const SizedBox height4 = SizedBox(height: 4.0);
const SizedBox height6 = SizedBox(height: 6.0);
const SizedBox height8 = SizedBox(height: 8.0);
const SizedBox height10 = SizedBox(height: 10.0);
const SizedBox height12 = SizedBox(height: 12.0);
const SizedBox height14 = SizedBox(height: 14.0);
const SizedBox height15 = SizedBox(height: 15.0);
const SizedBox height16 = SizedBox(height: 16.0);
const SizedBox height18 = SizedBox(height: 18.0);
const SizedBox height20 = SizedBox(height: 20.0);
const SizedBox height23 = SizedBox(height: 23.0);
const SizedBox height25 = SizedBox(height: 25.0);
const SizedBox height30 = SizedBox(height: 30.0);
const SizedBox height40 = SizedBox(height: 40.0);
const SizedBox height60 = SizedBox(height: 60.0);
const SizedBox width4 = SizedBox(width: 4.0);
const SizedBox width6 = SizedBox(width: 6.0);
const SizedBox width8 = SizedBox(width: 8.0);
const SizedBox width10 = SizedBox(width: 10.0);
const SizedBox width12 = SizedBox(width: 12.0);
const SizedBox width14 = SizedBox(width: 14.0);
const SizedBox width15 = SizedBox(width: 15.0);
const SizedBox width16 = SizedBox(width: 16.0);
const SizedBox width18 = SizedBox(width: 18.0);
const SizedBox width20 = SizedBox(width: 20.0);
const SizedBox width50 = SizedBox(width: 50.0);
